# https://taskfile.dev

version: '3'

dotenv:
  - .env

tasks:
  setup:
    cmds:
      - task: setup.backend
      - task: setup.frontend

  setup.backend:
    internal: true
    cmds:
      - docker-compose build

  setup.frontend:
    internal: true
    dir: frontend
    cmds:
      - echo "VITE_API_URL=http://0.0.0.0" > .env.local
      - npm ci

  makemigration:
    cmds:
      - docker-compose exec web alembic -c storage/alembic.ini revision --autogenerate {{.CLI_ARGS}}

  migrate:
    cmds:
      - docker-compose exec web alembic -c storage/alembic.ini upgrade head

  shell:
    cmds:
      - docker-compose exec web python shell.py
