# https://taskfile.dev

version: '3'

tasks:
  makemigration:
    dir: server
    cmds:
      - docker-compose run --rm web bash -c "sleep 2; alembic -c core/db/alembic.ini revision --autogenerate {{.CLI_ARGS}}"

  migrate:
    dir: server
    cmds:
      - docker-compose run --rm web bash -c "sleep 2; alembic -c core/db/alembic.ini upgrade {{.CLI_ARGS}}"

  shell:
    dir: server
    cmds:
      - docker-compose exec web python server_shell.py
