POST http://localhost:8066/auth/jwt/create/
Content-Type: application/json

{
  "username": "user",
  "password": "meowmeowmeow"
}

> {% client.global.set("user_token", response.body.access); %}

###
POST http://localhost:8066/auth/jwt/create/
Content-Type: application/json

{
  "username": "superuser",
  "password": "superuser"
}

> {% client.global.set("superuser_token", response.body.access); %}

###
GET http://localhost:8066/api/v1/userproducts/
Content-Type: application/json
Authorization: JWT {{superuser_token}}

> {% client.test("Returns all UserProducts", () => { client.assert(response.body.length === 2) }) %}

###
GET http://localhost:8066/api/v1/userproducts/?username=superuser
Content-Type: application/json
Authorization: JWT {{superuser_token}}

> {% client.test("Returns superuser's UserProducts", () => { client.assert(response.body.length === 1) }) %}

###
GET http://localhost:8066/api/v1/userproducts/?username=user
Content-Type: application/json
Authorization: JWT {{superuser_token}}

> {% client.test("Returns user's UserProducts", () => { client.assert(response.body.length === 1) }) %}

###
GET http://localhost:8066/api/v1/userproducts/?username=nouser
Content-Type: application/json
Authorization: JWT {{superuser_token}}

> {% client.test("Returns user's UserProducts", () => { client.assert(!response.body.length) }) %}


### Get user's products
GET http://localhost:8066/api/v1/userproducts/
Content-Type: application/json
Authorization: JWT {{user_token}}

> {% client.test("Returns user's UserProducts", () => { client.assert(response.body.length === 1) }) %}

###
GET http://localhost:8066/api/v1/userproducts/?username=superuser
Content-Type: application/json
Authorization: JWT {{user_token}}

> {% client.test("Do not return superuser's UserProducts", () => { client.assert(response.status === 403) }) %}

###
GET http://localhost:8066/api/v1/userproducts/?username=user
Content-Type: application/json
Authorization: JWT {{user_token}}

> {% client.test("Returns user's UserProducts", () => { client.assert(response.body.length === 1) }) %}

###
GET http://localhost:8066/api/v1/userproducts/?username=nouser
Content-Type: application/json
Authorization: JWT {{user_token}}

> {% client.test("Do not return nouser's UserProducts", () => { client.assert(response.status === 403) }) %}