# https://taskfile.dev

version: '3'

dotenv:
  - .env

tasks:
  makemigration:
    dir: treats
    cmds:
      - alembic -c storage/alembic.ini revision --autogenerate {{.CLI_ARGS}}

  migrate:
    dir: treats
    cmds:
      - alembic -c storage/alembic.ini upgrade {{.CLI_ARGS}}

  shell:
    cmds:
      - docker-compose exec web python server_shell.py

  run:
    dir: treats
    cmds:
      - uvicorn --port 8055 --reload --factory main:create_app