# https://taskfile.dev

version: '3'

dotenv:
  - .env

tasks:
  install:
    dir: treats
    cmds:
      - poetry install --no-root --only main,dev

  build.dev:
    cmds:
      - docker-compose build

  build:
    cmds:
      - docker-compose -f docker-compose.yml build

  makemigration:
    cmds:
      - docker-compose exec web alembic -c storage/alembic.ini revision --autogenerate {{.CLI_ARGS}}

  migrate:
    cmds:
      - docker-compose exec web alembic -c storage/alembic.ini upgrade head

  shell:
    cmds:
      - docker-compose exec web python shell.py

  web.shell:
    cmds:
      - docker-compose exec web bash

  up:
    cmds:
      - docker-compose up -d web db
      - task: migrate
      - docker-compose up -d watcher
