# https://taskfile.dev

version: '3'

dotenv:
  - .env

tasks:
  makemigration:
    cmds:
      - docker-compose exec web alembic -c storage/alembic.ini revision --autogenerate {{.CLI_ARGS}}

  migrate:
    cmds:
      - docker-compose exec web alembic -c storage/alembic.ini upgrade head

  shell:
    cmds:
      - docker-compose exec web python shell.py

  up:
    cmds:
      - docker-compose up -d web db
      - task: migrate
      - docker-compose up -d watcher
