# Generated by Django 4.2.2 on 2023-06-12 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scraper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entrypoint', models.CharField(max_length=256)),
                ('retailer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='products.retailer')),
            ],
        ),
    ]
