# Generated by Django 4.2.2 on 2023-06-18 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scraper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entrypoint', models.CharField(choices=[('scrapers.PerekrestokScraper', 'scrapers.PerekrestokScraper')], max_length=256)),
                ('config', models.JSONField(blank=True, default=dict)),
            ],
        ),
    ]
