# Generated by Django 4.2.2 on 2023-06-22 21:28

from django.db import migrations
from constance import config


def add_perekrestok_scraper(apps, schema_editor):
    scraper_model = apps.get_model("scraping.Scraper")
    scraper_model.objects.get_or_create(
        entrypoint="scrapers.PerekrestokScraper",
        defaults=dict(config=dict(API_BASE_URL=config.PEREKRESTOK_API_URL))
    )


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0001_initial'),
    ]

    operations = [migrations.RunPython(add_perekrestok_scraper)]
