# Generated by Django 4.2.2 on 2023-06-21 23:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scraping', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstore',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
        migrations.AddField(
            model_name='userproduct',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='store',
            name='retailer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stores', to='products.retailer'),
        ),
        migrations.AddField(
            model_name='retailer',
            name='scraper',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='scraping.scraper'),
        ),
        migrations.AddField(
            model_name='product',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='products', to='products.store'),
        ),
        migrations.AddField(
            model_name='price',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='products.product'),
        ),
        migrations.AddConstraint(
            model_name='userstore',
            constraint=models.UniqueConstraint(models.F('user'), models.F('store'), name='uniq_user_store'),
        ),
        migrations.AddConstraint(
            model_name='userproduct',
            constraint=models.UniqueConstraint(models.F('user'), models.F('product'), name='uniq_user_product'),
        ),
        migrations.AddConstraint(
            model_name='store',
            constraint=models.UniqueConstraint(models.F('retailer'), models.F('external_id'), name='uniq_retailer'),
        ),
    ]
