# Generated by Django 4.2.2 on 2023-06-22 22:37

from django.db import migrations


def add_perekrestok_retailer(apps, schema_editor):
    retailer_model = apps.get_model("products.Retailer")
    scraper_model = apps.get_model("scraping.Scraper")

    scraper = scraper_model.objects.get(entrypoint="scrapers.PerekrestokScraper")
    retailer_model.objects.create(
        title="perekrestok",
        display_title="Перекресток",
        product_url_pattern=r"^https://(w{3}\.)?perekrestok\.ru/cat/.+$",
        scraper=scraper,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_initial'),
        ('scraping', '0002_add_perekrestok_scraper'),
    ]

    operations = [migrations.RunPython(add_perekrestok_retailer)]
