# Generated by Django 4.2.2 on 2023-06-18 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_value_price_current_price_old'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='old',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
