# Generated by Django 4.2.2 on 2023-06-22 00:00

from django.db import migrations
from django.conf import settings
import os


def add_default_superuser(apps, schema_editor):
    user_model = apps.get_model(settings.AUTH_USER_MODEL)
    email = os.environ.get("DEFAULT_SUPERUSER_EMAIL", "superuser@example.com")
    password = os.environ.get("DEFAULT_SUPERUSER_PASSWORD", "superuser")
    user_model.objects.create_superuser(email=email, password=password)


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [migrations.RunPython(add_default_superuser)]
